#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PizzaAppMVVM.Resource", IsApplication=true)]

namespace PizzaAppMVVM
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::PizzaAppMVVM.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::PizzaAppMVVM.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int DisplayText = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int GoBackButton = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int ImageViewImage = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int LinearLayoutMain = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int ListViewProducts = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int MainActivityProgressBar = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int MyButton = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int NavigateButton = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int TextViewAdvertising = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int TextViewAvailable = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int TextViewSubtitle = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int TextViewTitle = 2131034120;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Page2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Page3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ProductTemplate = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
